### ISSUE TITLE
This occurs when you try to logout using the /logout or logout in the apartment it would throw you a client side error stating the issue I mentioned above and it also appears on the server console too

### ISSUE THREAD

**Issue by MonkeyWhisper** [Project-Sloth/ps-buffs#5]
This occurs when you try to logout using the /logout or logout in the apartment it would throw you a client side error stating the issue I mentioned above and it also appears on the server console too

_Originally posted by @AnishBplayz in https://github.com/Project-Sloth/ps-buffs/issues/4#issuecomment-1491886891_

**Comment by MonkeyWhisper** [comment]
@AnishBplayz, I just tried /logout and it didn't happen. 

Can you tell me if the buffs are part of a script or where it is being triggered?

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/ps-buffs/pull/4

**Comment by AnishBplayz** [comment]
Maybe give me some time monkey i will present you a preview to make it easier to understand ?

**Comment by MonkeyWhisper** [comment]
> Maybe give me some time monkey i will present you a preview to make it easier to understand ?

Yeah sure, it'll be helpful if you can send where the buffs are being applied because it looks like the issue might be from your other scripts not sending correct data to the server once the player drops

**Comment by xFutte** [comment]
It could be a simple timing issue.

**Comment by AnishBplayz** [comment]
![image](https://user-images.githubusercontent.com/91739770/229264508-aaf47a7c-560b-4bd1-83d2-1f8250d0d553.png)
I get this when try to logout without the workaround... does this help ?

**Comment by MonkeyWhisper** [comment]
> ![image](https://user-images.githubusercontent.com/91739770/229264508-aaf47a7c-560b-4bd1-83d2-1f8250d0d553.png) I get this when try to logout without the workaround... does this help ?

That's ps-hud?

**Comment by AnishBplayz** [comment]
Yup when i try to logout after reinstalling the ps-buffs i still face this issue and after applying the fix mentioned in the PR it doesn't... I am sure it is something with the callback

**Comment by MonkeyWhisper** [comment]
You need to provide full source code and what is being triggered, because that screenshot does not help at all.

**Comment by MonkeyWhisper** [comment]
Tell me exactly how to duplicate it and get this error

> Yup when i try to logout after reinstalling the ps-buffs i still face this issue and after applying the fix mentioned in the PR it doesn't... I am sure it is something with the callback

**Comment by AnishBplayz** [comment]
Sure i will be back with a preview about the issue

**Comment by AnishBplayz** [comment]
https://imgur.com/a/Y9vo6wk

So I fresh installed QBCore on my system and here you go with the preview the issue still persists

**Comment by AnishBplayz** [comment]
> ![image](https://user-images.githubusercontent.com/91739770/229264508-aaf47a7c-560b-4bd1-83d2-1f8250d0d553.png) I get this when try to logout without the workaround... does this help ?

This thing appears sometimes like once in five times when you try to logout, you get this error

**Comment by MonkeyWhisper** [comment]
> > ![image](https://user-images.githubusercontent.com/91739770/229264508-aaf47a7c-560b-4bd1-83d2-1f8250d0d553.png) I get this when try to logout without the workaround... does this help ?
> 
> This thing appears sometimes like once in five times when you try to logout, you get this error

How is this related to ps-buffs? You're showing screenshots, not code or any prints that are helpful?

**Comment by AnishBplayz** [comment]
By applying the fix mentioned in my PR this never appears for me after then... i really am not sure how it is related to ps-buffs but it fixes with this ps-buff PR of mine.... also i have shown a preview of the ps-buff error in server side in my previous comment.

**Comment by xFutte** [comment]
> By applying the fix mentioned in my PR this never appears for me after then... i really am not sure how it is related to ps-buffs but it fixes with this ps-buff PR of mine.... also i have shown a preview of the ps-buff error in server side in my previous comment.

No, it doesn't fix it. It just never executes the part of the code that is an issue.

**Comment by AnishBplayz** [comment]
True, since if the player has unloaded or unavailable then it doesn't have to execute that part of code right ?
